version: 3.8

services:
  dev:
    container_name: bleek-dot-tech-server
    image: bleek-dot-tech-server:1.0.0
    build:
      context:
        target: development
        dockerfile: ./Dockerfile
      command: npm run start:debug
      ports:
        - 3000:3000
        - 9229:9229
      networks:
        - nestjs-network
      volumes:
        - .:/usr/brand/Documents/projects/Node.js/bleek-dot-tech-server
        - /usr/brand/Documents/projects/Node.js/bleek-dot-tech-server/node_modules
      restart: unless-stopped
  prod:
    container_name: bleek-dot-tech-server
    image: bleek-dot-tech-server:1.0.0
    build:
      context:
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - .:/usr/brand/Documents/projects/Node.js/bleek-dot-tech-server
      - /usr/brand/Documents/projects/Node.js/bleek-dot-tech-server/node_modules
    restart: unless-stopped

networks:
  nestjs-network:
